# Application
spring.application.name=govpay-portal-api

# Server
server.port=8080
server.servlet.context-path=/govpay/frontend/api/pagamento/rs/public/v2

# SpringDoc OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha

# Logging
logging.level.root=INFO
logging.level.it.govpay=DEBUG
